import '../models/user_model.dart';
import '../models/post_model.dart';
import '../models/notification_model.dart';

class StaticDataService {
  static final List<UserModel> users = [
    UserModel(
      id: '1',
      name: 'Sarah Johnson',
      email: 'sarah@example.com',
      bio: 'Digital nomad | Coffee enthusiast | Photography lover',
      profileImageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      followersCount: 1250,
      followingCount: 340,
      postsCount: 89,
      createdAt: DateTime.now().subtract(const Duration(days: 365)),
    ),
    UserModel(
      id: '2',
      name: 'Michael Chen',
      email: 'michael@example.com',
      bio: 'Tech entrepreneur | Building the future | AI enthusiast',
      profileImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      followersCount: 8540,
      followingCount: 120,
      postsCount: 234,
      createdAt: DateTime.now().subtract(const Duration(days: 500)),
    ),
    UserModel(
      id: '3',
      name: 'Emma Wilson',
      email: 'emma@example.com',
      bio: 'Artist | Nature lover | Spreading positivity',
      profileImageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      followersCount: 3200,
      followingCount: 890,
      postsCount: 156,
      createdAt: DateTime.now().subtract(const Duration(days: 200)),
    ),
    UserModel(
      id: '4',
      name: 'James Rodriguez',
      email: 'james@example.com',
      bio: 'Fitness coach | Healthy lifestyle advocate | Runner',
      profileImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      followersCount: 5670,
      followingCount: 445,
      postsCount: 312,
      createdAt: DateTime.now().subtract(const Duration(days: 450)),
    ),
    UserModel(
      id: '5',
      name: 'Olivia Martinez',
      email: 'olivia@example.com',
      bio: 'Food blogger | Recipe creator | Travel foodie',
      profileImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      followersCount: 12300,
      followingCount: 234,
      postsCount: 567,
      createdAt: DateTime.now().subtract(const Duration(days: 600)),
    ),
  ];

  static final List<PostModel> posts = [
    PostModel(
      id: '1',
      content: 'Just finished an amazing hike in the mountains! The view from the top was absolutely breathtaking. Nature never fails to inspire me. 🏔️ #hiking #nature #adventure',
      mediaUrls: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800'],
      author: users[0],
      likesCount: 234,
      commentsCount: 45,
      sharesCount: 12,
      isLiked: true,
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      category: 'Travel',
    ),
    PostModel(
      id: '2',
      content: 'Excited to announce that our startup just closed Series A funding! Thank you to everyone who believed in our vision. The journey is just beginning! 🚀',
      mediaUrls: [],
      author: users[1],
      likesCount: 1520,
      commentsCount: 189,
      sharesCount: 78,
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      category: 'Business',
    ),
    PostModel(
      id: '3',
      content: 'New artwork completed! This piece represents the connection between humans and nature. Took me 3 weeks to finish. What do you think? 🎨',
      mediaUrls: [
        'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
        'https://images.unsplash.com/photo-1549887534-1541e9326642?w=800',
      ],
      author: users[2],
      likesCount: 892,
      commentsCount: 67,
      sharesCount: 34,
      isLiked: true,
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      category: 'Art',
    ),
    PostModel(
      id: '4',
      content: 'Morning workout done! Remember, consistency is key. Your body can do anything, its your mind you need to convince. 💪 #fitness #motivation #healthylifestyle',
      mediaUrls: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800'],
      author: users[3],
      likesCount: 567,
      commentsCount: 89,
      sharesCount: 23,
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      category: 'Fitness',
    ),
    PostModel(
      id: '5',
      content: 'Made this incredible homemade pasta from scratch today! The secret is in the fresh ingredients and lots of love. Recipe coming soon on my blog! 🍝',
      mediaUrls: [
        'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800',
      ],
      author: users[4],
      likesCount: 1123,
      commentsCount: 156,
      sharesCount: 89,
      isLiked: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      category: 'Food',
    ),
    PostModel(
      id: '6',
      content: 'Working from this beautiful cafe today. Sometimes a change of scenery is all you need to boost productivity! ☕ #remotework #digitalnomad',
      mediaUrls: ['https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800'],
      author: users[0],
      likesCount: 345,
      commentsCount: 23,
      sharesCount: 8,
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 5)),
      category: 'Lifestyle',
    ),
    PostModel(
      id: '7',
      content: 'The future of AI is here. Just witnessed an incredible demo of the latest language models. We are living in exciting times! 🤖',
      mediaUrls: [],
      author: users[1],
      likesCount: 2340,
      commentsCount: 312,
      sharesCount: 156,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      category: 'Technology',
    ),
    PostModel(
      id: '8',
      content: 'Sunset painting session by the lake. These moments of peace and creativity are priceless. 🌅',
      mediaUrls: [
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
      ],
      author: users[2],
      likesCount: 678,
      commentsCount: 45,
      sharesCount: 21,
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 8)),
      category: 'Art',
    ),
  ];

  static final List<PostModel> trendingPosts = [
    posts[1],
    posts[6],
    posts[4],
    posts[2],
  ];

  static final List<NotificationModel> notifications = [
    NotificationModel(
      id: '1',
      type: NotificationType.like,
      title: 'New Like',
      message: 'liked your post about hiking',
      actorName: 'Michael Chen',
      actorImageUrl: users[1].profileImageUrl,
      targetId: '1',
      createdAt: DateTime.now().subtract(const Duration(minutes: 15)),
    ),
    NotificationModel(
      id: '2',
      type: NotificationType.comment,
      title: 'New Comment',
      message: 'commented: "Amazing view! Where is this?"',
      actorName: 'Emma Wilson',
      actorImageUrl: users[2].profileImageUrl,
      targetId: '1',
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
    ),
    NotificationModel(
      id: '3',
      type: NotificationType.follow,
      title: 'New Follower',
      message: 'started following you',
      actorName: 'James Rodriguez',
      actorImageUrl: users[3].profileImageUrl,
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    NotificationModel(
      id: '4',
      type: NotificationType.mention,
      title: 'Mentioned You',
      message: 'mentioned you in a comment',
      actorName: 'Olivia Martinez',
      actorImageUrl: users[4].profileImageUrl,
      targetId: '5',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    NotificationModel(
      id: '5',
      type: NotificationType.share,
      title: 'Post Shared',
      message: 'shared your post',
      actorName: 'Michael Chen',
      actorImageUrl: users[1].profileImageUrl,
      targetId: '3',
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    NotificationModel(
      id: '6',
      type: NotificationType.like,
      title: 'New Like',
      message: 'and 24 others liked your post',
      actorName: 'Emma Wilson',
      actorImageUrl: users[2].profileImageUrl,
      targetId: '3',
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 5)),
    ),
  ];

  static final List<String> categories = [
    'All',
    'Technology',
    'Travel',
    'Food',
    'Art',
    'Fitness',
    'Business',
    'Lifestyle',
  ];

  static UserModel get currentUser => UserModel(
    id: 'current',
    name: 'John Doe',
    email: 'john@example.com',
    bio: 'App developer | Tech enthusiast | Building cool things',
    profileImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    followersCount: 542,
    followingCount: 128,
    postsCount: 34,
    createdAt: DateTime.now().subtract(const Duration(days: 180)),
  );
}